name: Continuous Integration Dockerized Tests

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/*.md'  # Ignore changes to Markdown files
  pull_request:
    paths-ignore:
      - '**/*.md'  # Ignore changes to Markdown files

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:latest
        ports:
          - 2375:2375

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build Docker Image for Tests
        run: docker build --target test --tag my-test-image .

      - name: Run Unit and Integration Tests
        run: docker run my-test-image


  publish:
    name: Publish Docker Image
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build --target production --tag ${{ secrets.DOCKER_USERNAME }}/my-image:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
      
      - name: Get webhook url and run curl command
        run: |
          curl -dH --fail -X POST '${{ secrets.WEBHOOK_URL }}'
